### ISSUE TITLE
To-Do List for Python

### ISSUE THREAD

**Issue by SuperSajuuk** [Azareal/SajuukBot#11]
This is more of a personal to-do list, copied from my server's admin channel:

**Under Consideration/In Progress**
- [ ] Improve the code base. This includes: simplification of argument processing (eg using .split() and not .replace() where .replace() isn't necessary), tidying up functions (splitting large functions into smaller, more specific ones, where appropriate), putting the functions in the appropriate files (eg admin related functions in admin.py) and so on.

**Completed**
- [x] Disallow double actions (ie don't ban when user is already banned)
- [x] Re-implement the "public welcome message" functionality. (Default: Off. Data stored in options dict, not database, making it easier to update)
- [x] End permamutes by command (`!mute end USERNAME`)
- [x] Make `give them quotes` configurable with channel ID at the end
- [x] Command Prefixes
- [x] Re-implement the dev.py file for developer commands
- [x] Tags storage system (!tag add name content).
- [x] !jumbo command.
- [x] Emoji Spam Filter.
- [x] Simplification of bot responses
- [x] Support "role persist".
- [x] Implement "infractions" storage (related to above, but need `!inf search` to get data)
- [x] Implement "temporary" mutes

**Comment by SuperSajuuk** [comment]
Current project is to write the tags system. Originally, the intention was to make this global, but tags will now be stored in the database per guild (so you won't be able to retrieve a tag for another guild).

**Comment by SuperSajuuk** [comment]
The bot now automatically censors invite links that aren't "approved". There is an internal bot list for whitelisted servers (mostly official discords like Discord Devs, Discord Testers, Discord API etc), but this is also combined by a per-guild list (configurable with `!update append/overwrite invite_whitelist listofcodeshere`)

**Comment by SuperSajuuk** [comment]
Implemented an emoji spam filter. Currently working on cleaning up the code, alongside implementing an option to turn on/off modules for those servers which don't need them.

**Comment by SuperSajuuk** [comment]
Role persist has been quickly added to the bot's repertoire of functionality. Working on some fixes to on_member_update and there'll probably be a commit over the weekend.

**Comment by SuperSajuuk** [comment]
Commit has been pushed with many bug fixes and implementation of some features. Key notes:
- Bot responses are NOT handled by a function, as planned.
- `!inf search` is just `!inf`: the "search" parameter is either `user` or `id`, depending on what to search.
- Implemented new files, and other useful functionality for mods and admins of their servers.

**Comment by SuperSajuuk** [comment]
Current plan for the bot is to implement tempmuting. This will allow for a user to be muted for a temporary amount of time (say 6 hours), then unmuted automatically.

By implementing tempmute functionality, I can look into a reminders based system (eg `!remind 6h my text to respond with in 6h`)

**Comment by SuperSajuuk** [comment]
Note for later: fix the final "on_server_join" message so it lists ALL required permissions:
* Manage Permissions (this must be set on specific channels, required for the !lock command)
* Manage Channels
* Kick Members
* Ban Members
* Read Messages
* Send Messages
* Manage Messages
* Embed Links (not really necessary, unless you plan on using !say)
* Attach Files (Needed for jumbo, can be set at role level, and per-channel).
* Use External Emoji

There are probably

**Comment by SuperSajuuk** [comment]
The public welcome functionality has been re-implemented, but does not use the database for storage now. It's stored in the options dictionary with the following keys:
* `welcome_members`
* `welcome_channel`
* `welcome_message`

The `welcome_members` option can be toggled using !enable/!disable respectively and the other two can be altered with the !update command respectively.

`welcome_channel` must be a single channel ID (you can get this with Right Click -> Copy ID on the channel you want to use).

Note that the `welcome_message` **must** (in some part of the string) include `{0.mention}` if you want the notification to mention the user. If you just want to print the user's name, use `{0.name}`. Missing either of these will print blank (and essentially useless) messages to the associated channel that won't tell anyone anything.

**Comment by SuperSajuuk** [comment]
Latest commit mostly completes the bots functionality and fixes bugs. At this point, bot development will slow and be mostly restricted to minor bug fixes and tweaks, with little new features being added at this time, unless there is demand.
