### ISSUE TITLE
To-Do list

### ISSUE THREAD

**Issue by SuperSajuuk** [Azareal/SajuukBot#8]
Basic list of things the first bot iteration will do:

- [ ] Greet new members when they join.
- [ ] Basic commands to manipulate bot options (initial will probably store this in a file before it's moved to a database solution, with file as backup if no db connection exists)
- [ ] Moderational settings (no caps, no swearing)

Please check here to see what's being done and add a comment if you are adding a new feature (or you can edit this ticket directly if you have the permissions).

**Comment by SuperSajuuk** [comment]
This is more of a to-do list for go. I'll make a separate issue for the python build. 👍

**Comment by SuperSajuuk** [comment]
Closing this, as single ticket issues like this are something that dont' work out well. The best way is to create separate tickets for each thing, categorise appropriately and use cards on the project to sort things by features, bugs and high priority issues. :)
